export enum Tool {
  SELECT = 'SELECT',
  LINE = 'LINE',
  RECTANGLE = 'RECTANGLE',
  CIRCLE = 'CIRCLE',
  MOVE = 'MOVE',
  SCALE = 'SCALE',
  ERASER = 'ERASER',
  IMAGE_IMPORT = 'IMAGE_IMPORT',
  ROTATE = 'ROTATE',
  MEASUREMENT = 'MEASUREMENT',
}
